//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Birth
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Birth()
        {
            this.ServiceManagementToBirth = new HashSet<ServiceManagementToBirth>();
        }
    
        public long UserId { get; set; }
        public System.DateTime BirthDateOfBaby { get; set; }
        public string BoyOrGirl { get; set; }
        public Nullable<long> NumOfBabies { get; set; }
        public long BirthId { get; set; }
    
        public virtual Mother Mother { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceManagementToBirth> ServiceManagementToBirth { get; set; }
    }
}
