//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mother
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mother()
        {
            this.Birth = new HashSet<Birth>();
        }
    
        public long UserId { get; set; }
        public Nullable<int> NumOfChildren { get; set; }
        public Nullable<long> Kosher1 { get; set; }
        public Nullable<long> Kosher2 { get; set; }
        public Nullable<long> Kosher3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Birth> Birth { get; set; }
        public virtual Kosher Kosher { get; set; }
        public virtual Kosher Kosher4 { get; set; }
        public virtual Kosher Kosher5 { get; set; }
        public virtual Users Users { get; set; }
    }
}
