//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceAndDaysToVolunteer
    {
        public long UserId { get; set; }
        public Nullable<System.TimeSpan> BeginningTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public long ServiceId { get; set; }
        public long ServiceAndDaysToVolunteerId { get; set; }
        public Nullable<long> DayId { get; set; }
    
        public virtual Days Days { get; set; }
        public virtual Volunteer Volunteer { get; set; }
        public virtual Services Services { get; set; }
    }
}
