//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceManagementToBirth
    {
        public long BirthId { get; set; }
        public System.DateTime BirthDateOfService { get; set; }
        public Nullable<System.TimeSpan> BeginningTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public long ServiceId { get; set; }
        public int StatusRequest { get; set; }
        public long ServiceManagementId { get; set; }
    
        public virtual Birth Birth { get; set; }
        public virtual ServiceVolunteerToBirth ServiceVolunteerToBirth { get; set; }
    }
}
