//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public long UserId { get; set; }
        public long RoleId { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public long Phone { get; set; }
        public string Address { get; set; }
        public long NumOfHouse { get; set; }
        public string Locality { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int Active { get; set; }
        public string FirstName { get; set; }
    
        public virtual Mother Mother { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual Volunteer Volunteer { get; set; }
    }
}
